In [17]:
import csv
import pandas as pd
from PIL import Image
test = pd.read_csv("input/data/train/train.csv")
test.head()

       id  gender   race  age                    path
0  000001  female  Asian   45  000001_female_Asian_45
1  000002  female  Asian   52  000002_female_Asian_52
2  000004    male  Asian   54    000004_male_Asian_54
3  000005  female  Asian   58  000005_female_Asian_58
4  000006  female  Asian   59  000006_female_Asian_59

In [21]:
f = open("input/data/train/train.csv")
name = 0
for i in csv.reader(f):
  if i[1] == 'male':
    if int(i[3]) < 30:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/00/{name}.jpg")
            name += 1
        except:
            continue
    elif 30 <= int(i[3]) < 60:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/01/{name}.jpg")
            name += 1
        except:
            continue
    elif int(i[3]) >= 60:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/02/{name}.jpg")
            name += 1
        except:
            continue
    try:
        img = Image.open(f"input/data/train/images/{i[4]}/incorrect_mask.jpg")
        if int(i[3]) < 30:
          img.save(f"classification/06/{name}.jpg")
          name += 1
        elif 30 <= int(i[3]) < 60:
          img.save(f"classification/07/{name}.jpg")
          name += 1
        elif int(i[3]) >= 60:
          img.save(f"classification/08/{name}.jpg")
          name += 1
        img = Image.open(f"input/data/train/images/{i[4]}/normal.jpg")
        if int(i[3]) < 30:
          img.save(f"classification/12/{name}.jpg")
          name += 1
        elif 30 <= int(i[3]) < 60:
          img.save(f"classification/13/{name}.jpg")
          name += 1
        elif int(i[3]) >= 60:
          img.save(f"classification/14/{name}.jpg")
          name += 1
    except:
        continue
  elif i[1] == 'female':
    if int(i[3]) < 30:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/03/{name}.jpg")
            name += 1
        except:
            continue
    elif 30 <= int(i[3]) < 60:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/04/{name}.jpg")
            name += 1
        except:
            continue
    elif int(i[3]) >= 60:
      for j in range(1,6):
        try:
            img = Image.open(f"input/data/train/images/{i[4]}/mask{j}.jpg")
            img.save(f"classification/05/{name}.jpg")
            name += 1
        except:
            continue
    try:
        img = Image.open(f"input/data/train/images/{i[4]}/incorrect_mask.jpg")
        if int(i[3]) < 30:
          img.save(f"classification/09/{name}.jpg")
          name += 1
        elif 30 <= int(i[3]) < 60:
          img.save(f"classification/10/{name}.jpg")
          name += 1
        elif int(i[3]) >= 60:
          img.save(f"classification/11/{name}.jpg")
          name += 1
        img = Image.open(f"input/data/train/images/{i[4]}/normal.jpg")
        if int(i[3]) < 30:
          img.save(f"classification/15/{name}.jpg")
          name += 1
        elif 30 <= int(i[3]) < 60:
          img.save(f"classification/16/{name}.jpg")
          name += 1
        elif int(i[3]) >= 60:
          img.save(f"classification/17/{name}.jpg")
          name += 1
    except:
        continue